AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/DuplicatedAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
